"""Worksheet round-trip for hand-authoring rubrics.

Rubric quality is the highest-leverage variable measured in this project:
on identical answers under identical judges, hand-authored rubrics lifted
inter-judge agreement from r = +0.30 to +0.62 and cut mean disagreement
from 1.26 to 0.80 points (Section 14.6). Machine drafts do not get there,
because `--draft-rubric` splits the answer into sentences and sentences
are compound, verdict-padded, and full of scaffolding.

So the rubrics have to be written by a person — and nobody should write
them by editing JSONL. There are two round-trips out to a human and back.

**The web form** (preferred). `scripts/rubric_server.py` serves the same
questions as a structured form: key points and errors are separate fields,
the draft is shown read-only, and nothing can be malformed on the way back.
Contributors need no software.

    python scripts/author_rubrics.py --export-tasks           # -> tasks.json
    #   ... deploy the server with it, contributors author ...
    python scripts/author_rubrics.py --ingest-submissions submissions.jsonl --dry-run
    python scripts/author_rubrics.py --ingest-submissions submissions.jsonl

**The text worksheet** (offline fallback, and what to use for yourself).

    python scripts/author_rubrics.py --emit 20            # thinnest categories first
    python scripts/author_rubrics.py --emit 10 --category "turn-structure walkthrough"
    python scripts/author_rubrics.py --fix-gold           # rewrite rubrics already IN the gold set
    python scripts/author_rubrics.py --ingest worksheet.txt

Selection defaults to whichever categories are furthest below target, so
coverage evens out without anyone tracking it by hand.

**The server never touches the gold set.** It reads an exported task file and
appends submissions to its own store; promoting them is a local step that runs
the same validation as a worksheet ingest. That keeps "gold means someone
reviewed it" true even when authoring happens on a public host.

See data/gold/SCHEMA.md for the four rules a good rubric follows.
"""

import argparse
import json
import re
import sys
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from common import (CR_VERSION, GLOSSARY_CANDIDATES_PATH, GLOSSARY_PATH,  # noqa: E402
                    GOLD_CANDIDATES_PATH, GOLD_PATH, WORKSHEETS_DIR,
                    is_hand_authored, lint_common_errors, normalize_record,
                    read_jsonl, stray_names, templatize, untemplatize,
                    write_jsonl_atomic)

CANDIDATES_PATH = GOLD_CANDIDATES_PATH
WORKSHEET_DIR = WORKSHEETS_DIR

BLOCK_RE = re.compile(r"^###\s+(?P<id>\S+)", re.M)
# A worksheet round-trips through email, Word, Google Docs and TextEdit before
# it comes back, and every one of those rewrites the bullet the template ships
# with. Measured: of seven ways a person plausibly writes a list, only a plain
# ASCII hyphen survived — the other six parsed to ZERO key points, and a block
# with no key points is silently skipped. That is the worst possible failure
# for contributed work: someone spends two hours and it vanishes without an
# error. Accept every bullet, and a bare line too: the KEY POINTS / COMMON
# ERRORS delimiters already establish that anything between them is content.
BULLET_RE = re.compile(r"^\s*(?:[-*+•·▪●–—]+|\d+[.)])\s*")
SECTION_RE = re.compile(
    r"^KEY POINTS:\s*$(?P<kp>.*?)^COMMON ERRORS:\s*$(?P<ce>.*?)(?=^###|\Z)",
    re.M | re.S,
)

HEADER = """# Rubric authoring worksheet

Fill in KEY POINTS and COMMON ERRORS under each question, then run:
    python scripts/author_rubrics.py --ingest {path}

The four rules (data/gold/SCHEMA.md):
  1. Fold the verdict into a substantive claim — never a bare "Yes"/"No".
  2. One atomic, independently checkable assertion per point.
  3. Cut scaffolding. Prefer 2-4 sharp points over 5-8 soft ones.
  4. COMMON ERRORS = the real trap, not the negation of a key point.

The DRAFT shown under each question is machine-generated by sentence-splitting
the answer. It is there to be rewritten, not kept. Leaving a block's KEY POINTS
empty skips that question.

Answers come from RulesGuru and are rules-verified; you are decomposing an
answer you can trust, not adjudicating the ruling.

================================================================================

"""

BLOCK = """### {id}   [{category} / {difficulty}]
{url}

QUESTION:
{question}

ANSWER:
{answer}

DRAFT (machine-generated — rewrite, do not keep):
{draft}

KEY POINTS:
-
-

COMMON ERRORS:
-
-

--------------------------------------------------------------------------------

"""


load_jsonl = read_jsonl  # one definition, in common.py


def load_pools(paths: list[Path]) -> list[dict]:
    """Every candidate across the pools, de-duplicated by id, first pool wins."""
    seen: dict[str, dict] = {}
    for path in paths:
        for rec in read_jsonl(path):
            seen.setdefault(rec["id"], rec)
    return list(seen.values())


# `definition recall` is the one category RulesGuru cannot supply: it is a
# database of *scenarios*, so "What does X mean?" never appears in it and the
# category sat at 1 record while the other seven reached 7-8.
#
# The Comprehensive Rules glossary is the natural source, and an authoritative
# one — the definition IS the verified answer, in WotC's own words. build_sft.py
# already derives synthetic training examples in exactly this shape; the same
# question template and the same redirect filter are reused rather than
# re-derived, so gold and SFT ask the category the same way.
REDIRECT_RE = re.compile(r"^See [^.]+\.$")
# Terms that cannot become a clean question. Two kinds, both measured over the
# 482 eligible entries:
#   * "(Obsolete)" — Damage Assignment Order, Totem Armor. The CR keeps these
#     so old cards resolve; asking a model to define them tests trivia about a
#     rule that no longer applies.
#   * bracketed or quoted templates — "Venture into [Quality]", "Partner with
#     [name]", Banding, "Bands with Other". The brackets are meta-syntax, and a
#     prompt containing them invites the model to copy them back, which is the
#     `[TARGET <x>]` failure that once scored correct plays as illegal.
UNUSABLE_TERM = re.compile(r"\(Obsolete\)|[\[\]\u201c\u201d]")


def glossary_candidates(glossary: list[dict], n: int, existing: set[str]) -> list[dict]:
    """Definition-recall candidates from the CR glossary, in gold-record shape.

    Only entries carrying `related_rules` are eligible. `rule_citations` is a
    required gold field validated against the pinned CR, so an entry without
    one cannot be promoted — 482 of the 739 glossary terms qualify, which is
    far more than this category needs.
    """
    pool = [g for g in glossary
            if g.get("related_rules")
            and not REDIRECT_RE.match(g["definition"])
            and len(g["definition"]) > 20
            and not UNUSABLE_TERM.search(g["term"])
            and f"gloss-{_slug(g['term'])}" not in existing]
    # Longest definitions first: a term the CR spends three sentences on has
    # more separable claims, and a rubric needs at least two key points. The
    # one-line definitions make for rubrics that restate themselves.
    pool.sort(key=lambda g: (-len(g["definition"]), g["term"]))
    out = []
    for g in pool[:n]:
        out.append({
            "id": f"gloss-{_slug(g['term'])}",
            "question": f'What does "{g["term"]}" mean in Magic: The Gathering?',
            "answer": g["definition"],
            "key_points": [],
            "common_errors": [],
            "rule_citations": g["related_rules"],
            "category": "definition recall",
            # Uniformly basic, deliberately. The first version graded on
            # definition length, which is not difficulty — and the threshold was
            # dead code besides, since the longest eligible definition is 397
            # characters against a 400 cutoff. Recalling a definition is a basic
            # task; a manufactured spread would make the difficulty column mean
            # two different things in one file. The resulting skew is a
            # composition fact to report, not to launder.
            "difficulty": "basic",
            "source": f"glossary:{g['term']}",
            "cr_version": CR_VERSION,
            "cards": [],
            "paraphrases": [],
            "needs_review": True,
            "needs_rubric_review": True,
        })
    return out


def _slug(term: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", term.lower()).strip("-")


def needs_authoring(record: dict) -> bool:
    """True when a gold record's rubric is still a machine draft."""
    return not is_hand_authored(record)


def pick_candidates(candidates: list[dict], gold: list[dict], n: int,
                    category: str | None, target: int) -> list[dict]:
    """Choose questions from whichever categories are furthest below target."""
    have = Counter(r["category"] for r in gold)
    # Key on rulesguru_id where there is one and on id otherwise: glossary-derived
    # candidates have no RulesGuru identity at all, and `c["rulesguru_id"]` on
    # one of those is a KeyError rather than a miss.
    taken = {r.get("rulesguru_id") for r in gold if r.get("rulesguru_id")}
    taken |= {r["id"] for r in gold}
    pool = [c for c in candidates if (c.get("rulesguru_id") or c["id"]) not in taken]
    if category:
        pool = [c for c in pool if c["category"] == category]

    by_cat: dict[str, list[dict]] = {}
    for c in pool:
        by_cat.setdefault(c["category"], []).append(c)
    # Stable, non-arbitrary order within a category: hardest first, since
    # advanced questions discriminate between systems more than basic ones.
    rank = {"advanced": 0, "intermediate": 1, "basic": 2}
    for v in by_cat.values():
        v.sort(key=lambda c: (rank.get(c["difficulty"], 3),
                              str(c.get("rulesguru_id") or c["id"])))

    picked: list[dict] = []
    while len(picked) < n and any(by_cat.values()):
        # Refill the category that is furthest from target each round.
        deficits = sorted(
            ((target - have[cat] - sum(1 for p in picked if p["category"] == cat), cat)
             for cat in by_cat if by_cat[cat]),
            key=lambda t: (-t[0], t[1]),
        )
        if not deficits:
            break
        _, cat = deficits[0]
        picked.append(by_cat[cat].pop(0))
    return picked


def export_tasks(records: list[dict], out_path: Path, gold_ids: set[str] | None = None) -> None:
    """Write the self-contained task file the rubric server reads.

    Self-contained on purpose. The server gets questions, verified answers and
    machine drafts — and nothing else. It has no gold set, no candidate file,
    no rules corpus and no card index, so a host running it cannot leak or
    corrupt any of them. Everything a contributor needs to see is here; nothing
    they must not reach is.

    **Records are normalized on the way out.** Gold was migrated to
    `Player A/B` with `card_slots`; the 1,202 candidates never were, and they
    are where every record past the first 39 comes from. Exporting them raw
    showed contributors "Arden controls..." next to gold's "Player A
    controls...", and shipped `card_slots: {}` even though `cards` was
    populated on 1,200 of them — so the card chips did nothing and no rubric
    written against a candidate got templated. Both defects were silent: the
    form worked, the rubric saved, validation passed.

    The promotion path applies the *same* function, so the slots a rubric was
    written against are the slots the gold record ends up with.
    """
    gold_ids = gold_ids or set()
    records = [normalize_record(r)[0] for r in records]
    tasks = [
        {
            "id": r["id"],
            "category": r["category"],
            "difficulty": r["difficulty"],
            "question": r["question"],
            "answer": r["answer"],
            # Shown read-only. It is a sentence-split of the answer and exists
            # to be argued with, not edited — Section 14.6 measured drafts of
            # exactly this kind scoring r = +0.30 against hand-written +0.62.
            "draft": [untemplatize(x, r.get("card_slots") or {})
                      for x in r.get("key_points") or []],
            "url": r.get("rulesguru_url", ""),
            # Membership, checked against the gold set. This was
            # `bool(r.get("cr_version"))` — but candidates carry `cr_version`
            # too (they are built against the same pinned CR), so every
            # candidate exported as `in_gold: True`. One field, two meanings:
            # "built against CR 2026-08-07" is not "a person promoted this".
            "in_gold": r["id"] in gold_ids,
            # The form needs the mapping in both directions: to show which card
            # occupies which slot, and to turn the names an author types back
            # into slots on save. Without it a fresh task file would render
            # "[[card1]]" as literal text.
            "card_slots": r.get("card_slots") or {},
        }
        for r in records
    ]
    payload = {"generated": datetime.now(timezone.utc).isoformat(timespec="seconds"),
               "count": len(tasks), "tasks": tasks}
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(payload, ensure_ascii=False, indent=1), encoding="utf-8")

    by_cat = Counter(t["category"] for t in tasks)
    print(f"{len(tasks)} tasks -> {out_path}")
    for cat, n in sorted(by_cat.items()):
        print(f"  {cat}: {n}")
    print(f"\nServe locally:  python scripts/rubric_server.py --tasks {out_path}")
    print(f"Deploy:         see deploy/README.md")


def read_submissions(path: Path) -> dict[str, dict]:
    """Collapse a submissions log into {id: latest rubric}.

    The server appends rather than rewrites, so a contributor revisiting a
    question leaves two rows. Last write wins, which matches what they saw in
    the form. Keeping the earlier rows means the log stays an audit trail.
    """
    latest: dict[str, dict] = {}
    for row in read_jsonl(path, missing_ok=False):
        rid = row.get("id")
        if not rid:
            continue
        kp = [s.strip() for s in row.get("key_points") or [] if s.strip()]
        if not kp:
            continue  # an explicit skip, same meaning as a blank worksheet block
        latest[rid] = {
            "key_points": kp,
            "common_errors": [s.strip() for s in row.get("common_errors") or [] if s.strip()],
            "author": (row.get("author") or "").strip(),
            "submitted": row.get("submitted", ""),
        }
    return latest


def emit(records: list[dict], out_path: Path) -> None:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    parts = [HEADER.format(path=out_path)]
    for r in records:
        draft = "\n".join(f"  - {p}" for p in r.get("key_points") or []) or "  (none)"
        parts.append(
            BLOCK.format(
                id=r["id"], category=r["category"], difficulty=r["difficulty"],
                url=r.get("rulesguru_url", ""), question=r["question"],
                answer=r["answer"], draft=draft,
            )
        )
    out_path.write_text("".join(parts), encoding="utf-8")

    by_cat = Counter(r["category"] for r in records)
    print(f"{len(records)} questions -> {out_path}")
    for cat, n in sorted(by_cat.items()):
        print(f"  {cat}: {n}")
    print(f"\nFill it in, then: python scripts/author_rubrics.py --ingest {out_path}")


def parse_worksheet(text: str) -> dict[str, dict]:
    """Read back {id: {key_points, common_errors}} for completed blocks only."""
    out: dict[str, dict] = {}
    starts = [(m.group("id"), m.start()) for m in BLOCK_RE.finditer(text)]
    for i, (rid, start) in enumerate(starts):
        end = starts[i + 1][1] if i + 1 < len(starts) else len(text)
        block = text[start:end]
        m = SECTION_RE.search(block)
        if not m:
            continue

        def bullets(s: str) -> list[str]:
            items = []
            for line in s.split("\n"):
                line = line.strip()
                # The block separator is a run of dashes, which looks exactly
                # like a bullet to a naive `startswith("-")` and got imported
                # as a key point on the first test. Same for underscores and
                # equals signs, which people use as separators too.
                if not line or set(line) <= {"-", "_", "=", "–", "—", "*"}:
                    continue
                v = BULLET_RE.sub("", line, count=1).strip()
                # Skip the empty "-" placeholders the template ships with.
                if v:
                    items.append(v)
            return items

        kp = bullets(m.group("kp"))
        if not kp:
            continue  # deliberately left blank -> skip, don't half-import
        out[rid] = {"key_points": kp, "common_errors": bullets(m.group("ce"))}
    return out


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--emit", type=int, default=0, help="write a worksheet of N questions")
    parser.add_argument("--fix-gold", action="store_true",
                        help="emit gold records whose rubric is still machine-drafted")
    parser.add_argument("--ingest", type=Path, default=None, help="read a completed worksheet back")
    parser.add_argument("--category", default=None, help="restrict --emit to one category")
    parser.add_argument("--target", type=int, default=15, help="per-category goal that drives selection")
    parser.add_argument("--candidates", type=Path, nargs="+",
                        default=[CANDIDATES_PATH, GLOSSARY_CANDIDATES_PATH],
                        help="candidate pools. Two by default: the RulesGuru scenarios and "
                             "the glossary-derived definition-recall questions, which "
                             "RulesGuru has none of.")
    parser.add_argument("--from-glossary", type=int, default=0, metavar="N",
                        help="derive N definition-recall candidates from the CR glossary "
                             "and append them to the glossary candidate pool")
    parser.add_argument("--gold", type=Path, default=GOLD_PATH)
    parser.add_argument("--out", type=Path, default=None)
    parser.add_argument("--author", default="", help="recorded in rubric_source, e.g. 'judge:LX'")
    parser.add_argument("--dry-run", action="store_true",
                        help="with --ingest/--ingest-submissions, print what would be imported "
                             "and change nothing. Use this on everything that comes back from "
                             "someone else.")
    parser.add_argument("--export-tasks", action="store_true",
                        help="write the task file rubric_server.py serves")
    parser.add_argument("--include-new", type=int, default=0, metavar="N",
                        help="with --export-tasks, also include N unused candidates so "
                             "contributors can grow the set, not only repair it")
    parser.add_argument("--ingest-submissions", type=Path, default=None, metavar="submissions.jsonl",
                        help="import what the rubric server collected. Attribution comes from "
                             "each submission, so one file can hold several authors.")
    args = parser.parse_args()

    gold = load_jsonl(args.gold)

    if args.fix_gold:
        stale = [r for r in gold if needs_authoring(r)]
        if not stale:
            print("every gold record already has a hand-authored rubric")
            return
        # --category splits the stale set so two people can work at once
        # without being handed the same records. Ingesting overwrites by id,
        # so overlapping worksheets mean whoever is ingested last silently
        # wins and the other person's work is discarded without a warning.
        name = "fix_gold.txt"
        if args.category:
            stale = [r for r in stale if r["category"] == args.category]
            if not stale:
                raise SystemExit(
                    f"no stale rubrics in category {args.category!r}. Present: "
                    + ", ".join(sorted({r['category'] for r in gold if needs_authoring(r)})))
            name = f"fix_gold_{args.category.replace('/', '-').replace(' ', '_')}.txt"
        out = args.out or WORKSHEET_DIR / name
        emit(stale, out)
        print("\nThese are already IN the gold set with machine-drafted rubrics —\n"
              "rewriting them raises the quality of the set you already have.")
        return

    if args.from_glossary:
        # Additive, like the RulesGuru snapshot: an existing candidate is never
        # rewritten, so a term already exported keeps the exact text a
        # contributor may be part-way through authoring against.
        existing = read_jsonl(GLOSSARY_CANDIDATES_PATH)
        have = {r["id"] for r in existing}
        drafted = glossary_candidates(read_jsonl(GLOSSARY_PATH, missing_ok=False),
                                      args.from_glossary, have)
        if not drafted:
            raise SystemExit("no eligible glossary terms left — every one with "
                             "related_rules is already a candidate")
        write_jsonl_atomic(GLOSSARY_CANDIDATES_PATH, existing + drafted)
        print(f"{len(drafted)} definition-recall candidates -> {GLOSSARY_CANDIDATES_PATH}"
              f"  ({len(existing)} -> {len(existing) + len(drafted)})")
        for d in drafted:
            print(f"  {d['id']:34s} [{d['difficulty']}] {d['question']}")
        print("\nNext: python scripts/author_rubrics.py --export-tasks --include-new N")
        return

    if args.emit:
        candidates = load_pools(args.candidates)
        if not candidates:
            raise SystemExit(f"no candidates in {args.candidates} — run scripts/rulesguru_to_gold.py first")
        picked = pick_candidates(candidates, gold, args.emit, args.category, args.target)
        if not picked:
            raise SystemExit("no unused candidates matched — try a different --category")
        name = f"author_{args.category.replace('/', '-').replace(' ', '_')}.txt" if args.category else "author.txt"
        emit(picked, args.out or WORKSHEET_DIR / name)
        return

    if args.export_tasks:
        pool = [r for r in gold if needs_authoring(r)]
        seen = {r["id"] for r in pool}
        if args.include_new:
            candidates = load_pools(args.candidates)
            if not candidates:
                raise SystemExit(f"no candidates in {args.candidates} — run rulesguru_to_gold.py first")
            pool += [c for c in pick_candidates(candidates, gold, args.include_new,
                                                args.category, args.target)
                     if c["id"] not in seen]
        if args.category:
            pool = [r for r in pool if r["category"] == args.category]
        if not pool:
            raise SystemExit("nothing to export — every gold rubric is hand-authored "
                             "and --include-new was not given")
        export_tasks(pool, args.out or WORKSHEETS_DIR / "tasks.json",
                     gold_ids={r["id"] for r in gold})
        return

    if args.ingest or args.ingest_submissions:
        if args.ingest_submissions:
            subs = read_submissions(args.ingest_submissions)
            authored = {rid: {"key_points": s["key_points"],
                              "common_errors": s["common_errors"]}
                        for rid, s in subs.items()}
            # Attribution comes from the submission, not the command line: a
            # single file holds work from several people, and crediting them
            # all to whoever ran the import would make the per-author
            # agreement breakdown in `eval.py --compare` meaningless.
            authors = {rid: s["author"] for rid, s in subs.items() if s["author"]}
            if not authored:
                raise SystemExit(f"no usable submissions in {args.ingest_submissions}")
            print(f"{len(authored)} submission(s) from "
                  f"{len(set(authors.values())) or 'unknown'} author(s)")
        else:
            authored = parse_worksheet(args.ingest.read_text(encoding="utf-8"))
            authors = {}
            if not authored:
                raise SystemExit("no completed blocks found — did you fill in KEY POINTS?")

        by_id = {r["id"]: r for r in gold}
        candidates = {c["id"]: c for c in load_pools(args.candidates)}
        def source_for(rid: str) -> str:
            who = authors.get(rid) or args.author
            s = f"hand-authored ({who})" if who else "hand-authored"
            return s + "; decomposed from the source's verified answer, not judge-reviewed"

        if args.dry_run:
            # Contributed worksheets come back from people who cannot check
            # the result themselves, so look before writing to the gold set.
            # `--ingest` overwrites rubrics in place and there is no undo.
            print(f"DRY RUN — {args.gold} will not be modified\n")
            for rid, rub in authored.items():
                where = ("rewrite" if rid in {r["id"] for r in gold}
                         else "promote" if rid in candidates
                         else "UNKNOWN ID")
                who = authors.get(rid) or args.author or "unattributed"
                # Normalized, for the same reason the promotion is: the rubric
                # being checked says "Player A", so checking it against a raw
                # candidate's "Arden" question would report every correct
                # rubric as naming a player the question never introduces.
                ref = by_id.get(rid)
                if ref is None and rid in candidates:
                    ref = normalize_record(candidates[rid], templatize_rubric=False)[0]
                ref = ref or {}
                # Expand [[cardN]] before showing OR linting. The answer keeps
                # real card names, so a templated rubric silently defeats
                # `lint_common_errors`: the Section 16.12 defect "Casts
                # [[card1]] at the opponent's face" no longer restates "Cast
                # Lightning Strike on ..." because the two are written in
                # different alphabets. Measured — the plain form warns, the
                # templated form does not.
                slots = ref.get("card_slots") or {}
                shown = {f: [untemplatize(x, slots) for x in rub[f]]
                         for f in ("key_points", "common_errors")}
                print(f"### {rid}  [{where}]  by {who}")
                for kp in shown["key_points"]:
                    print(f"    KP  {kp}")
                for ce in shown["common_errors"]:
                    print(f"    CE  {ce}")
                if len(rub["key_points"]) < 2:
                    print("    ^^ only 1 key point — the validator needs 2+, this would be skipped")
                if not rub["common_errors"]:
                    print("    ^^ no COMMON ERRORS — half the rubric's power is missing")
                # The wording defect Section 16.12 measured. Warn, never block:
                # the check is deliberately conservative and a clean result
                # means "no obvious defect", not "good rubric".
                for w in lint_common_errors({"answer": ref.get("answer", ""), **shown}):
                    print(f"    !!  {w}")
                stray = stray_names(ref.get("question", ""), ref.get("answer", ""),
                                    shown["key_points"] + shown["common_errors"])
                if stray:
                    print(f"    !!  {', '.join(stray)} — not in the question or its "
                          f"answer; check the player name is the right one")
                print()
            print(f"{len(authored)} block(s) parsed. Re-run without --dry-run to apply.")
            return

        updated = added = skipped = 0
        problems: list[str] = []
        for rid, rub in authored.items():
            if len(rub["key_points"]) < 2:
                problems.append(f"{rid}: only {len(rub['key_points'])} key point — the validator needs 2+")
                skipped += 1
                continue
            if rid in by_id:
                by_id[rid].update(key_points=rub["key_points"], common_errors=rub["common_errors"],
                                  rubric_source=source_for(rid), needs_rubric_review=False)
                updated += 1
            elif rid in candidates:
                # Normalize BEFORE attaching the rubric. The contributor wrote
                # against the exported task, which `export_tasks` normalized
                # with this same function — so the question they read said
                # "Player A" and the slots their card names collapsed into came
                # from this same `cards` list, in this same order. Promoting the
                # raw candidate instead would file a "Player A" rubric against
                # an "Arden" question, and drop the slots the rubric is written
                # in. The rubric itself is taken as submitted, not re-renamed.
                rec = normalize_record(candidates[rid], templatize_rubric=False)[0]
                rec.update(key_points=rub["key_points"], common_errors=rub["common_errors"],
                           rubric_source=source_for(rid), needs_rubric_review=False,
                           needs_review=True)
                gold.append(rec)
                added += 1
            else:
                problems.append(f"{rid}: not found in gold or candidates")
                skipped += 1

        with args.gold.open("w", encoding="utf-8") as f:
            for r in gold:
                f.write(json.dumps(r, ensure_ascii=False) + "\n")

        print(f"{added} promoted, {updated} rewritten, {skipped} skipped -> {args.gold}")
        no_errors = [rid for rid, r in authored.items() if not r["common_errors"]]
        if no_errors:
            print(f"\n{len(no_errors)} block(s) have no COMMON ERRORS. That field is half the "
                  f"rubric's power and cannot be derived from the answer — worth a second pass:")
            print("  " + ", ".join(no_errors[:8]))
        if problems:
            print(f"\n{len(problems)} problem(s):")
            for p in problems:
                print(f"  - {p}")
        print("\nNext: python scripts/validate_gold.py --to-eval")
        return

    parser.error("choose one of --emit, --fix-gold, or --ingest")


if __name__ == "__main__":
    main()
