"""Worksheet round-trip for hand-authoring rubrics.

Rubric quality is the highest-leverage variable measured in this project:
on identical answers under identical judges, hand-authored rubrics lifted
inter-judge agreement from r = +0.30 to +0.62 and cut mean disagreement
from 1.26 to 0.80 points (Section 14.6). Machine drafts do not get there,
because `--draft-rubric` splits the answer into sentences and sentences
are compound, verdict-padded, and full of scaffolding.

So the rubrics have to be written by a person — and nobody should write
them by editing JSONL. This emits a plain-text worksheet, one block per
question, and reads the completed file back:

    python scripts/author_rubrics.py --emit 20            # thinnest categories first
    python scripts/author_rubrics.py --emit 10 --category "turn-structure walkthrough"
    python scripts/author_rubrics.py --fix-gold           # rewrite rubrics already IN the gold set
    python scripts/author_rubrics.py --ingest worksheet.txt

Selection defaults to whichever categories are furthest below target, so
coverage evens out without anyone tracking it by hand.

See data/gold/SCHEMA.md for the four rules a good rubric follows.
"""

import argparse
import json
import re
import sys
from collections import Counter
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from common import GOLD_CANDIDATES_PATH, GOLD_PATH, read_jsonl

CANDIDATES_PATH = GOLD_CANDIDATES_PATH
WORKSHEET_DIR = Path("data/gold/worksheets")

BLOCK_RE = re.compile(r"^###\s+(?P<id>\S+)", re.M)
SECTION_RE = re.compile(
    r"^KEY POINTS:\s*$(?P<kp>.*?)^COMMON ERRORS:\s*$(?P<ce>.*?)(?=^###|\Z)",
    re.M | re.S,
)

HEADER = """# Rubric authoring worksheet

Fill in KEY POINTS and COMMON ERRORS under each question, then run:
    python scripts/author_rubrics.py --ingest {path}

The four rules (data/gold/SCHEMA.md):
  1. Fold the verdict into a substantive claim — never a bare "Yes"/"No".
  2. One atomic, independently checkable assertion per point.
  3. Cut scaffolding. Prefer 2-4 sharp points over 5-8 soft ones.
  4. COMMON ERRORS = the real trap, not the negation of a key point.

The DRAFT shown under each question is machine-generated by sentence-splitting
the answer. It is there to be rewritten, not kept. Leaving a block's KEY POINTS
empty skips that question.

Answers come from RulesGuru and are rules-verified; you are decomposing an
answer you can trust, not adjudicating the ruling.

================================================================================

"""

BLOCK = """### {id}   [{category} / {difficulty}]
{url}

QUESTION:
{question}

ANSWER:
{answer}

DRAFT (machine-generated — rewrite, do not keep):
{draft}

KEY POINTS:
-
-

COMMON ERRORS:
-
-

--------------------------------------------------------------------------------

"""


load_jsonl = read_jsonl  # one definition, in common.py


def needs_authoring(record: dict) -> bool:
    """True when a gold record's rubric is still a machine draft."""
    return not record.get("rubric_source")


def pick_candidates(candidates: list[dict], gold: list[dict], n: int,
                    category: str | None, target: int) -> list[dict]:
    """Choose questions from whichever categories are furthest below target."""
    have = Counter(r["category"] for r in gold)
    taken = {r.get("rulesguru_id") for r in gold if r.get("rulesguru_id")}
    pool = [c for c in candidates if c["rulesguru_id"] not in taken]
    if category:
        pool = [c for c in pool if c["category"] == category]

    by_cat: dict[str, list[dict]] = {}
    for c in pool:
        by_cat.setdefault(c["category"], []).append(c)
    # Stable, non-arbitrary order within a category: hardest first, since
    # advanced questions discriminate between systems more than basic ones.
    rank = {"advanced": 0, "intermediate": 1, "basic": 2}
    for v in by_cat.values():
        v.sort(key=lambda c: (rank.get(c["difficulty"], 3), c["rulesguru_id"]))

    picked: list[dict] = []
    while len(picked) < n and any(by_cat.values()):
        # Refill the category that is furthest from target each round.
        deficits = sorted(
            ((target - have[cat] - sum(1 for p in picked if p["category"] == cat), cat)
             for cat in by_cat if by_cat[cat]),
            key=lambda t: (-t[0], t[1]),
        )
        if not deficits:
            break
        _, cat = deficits[0]
        picked.append(by_cat[cat].pop(0))
    return picked


def emit(records: list[dict], out_path: Path) -> None:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    parts = [HEADER.format(path=out_path)]
    for r in records:
        draft = "\n".join(f"  - {p}" for p in r.get("key_points") or []) or "  (none)"
        parts.append(
            BLOCK.format(
                id=r["id"], category=r["category"], difficulty=r["difficulty"],
                url=r.get("rulesguru_url", ""), question=r["question"],
                answer=r["answer"], draft=draft,
            )
        )
    out_path.write_text("".join(parts), encoding="utf-8")

    by_cat = Counter(r["category"] for r in records)
    print(f"{len(records)} questions -> {out_path}")
    for cat, n in sorted(by_cat.items()):
        print(f"  {cat}: {n}")
    print(f"\nFill it in, then: python scripts/author_rubrics.py --ingest {out_path}")


def parse_worksheet(text: str) -> dict[str, dict]:
    """Read back {id: {key_points, common_errors}} for completed blocks only."""
    out: dict[str, dict] = {}
    starts = [(m.group("id"), m.start()) for m in BLOCK_RE.finditer(text)]
    for i, (rid, start) in enumerate(starts):
        end = starts[i + 1][1] if i + 1 < len(starts) else len(text)
        block = text[start:end]
        m = SECTION_RE.search(block)
        if not m:
            continue

        def bullets(s: str) -> list[str]:
            items = []
            for line in s.split("\n"):
                line = line.strip()
                # The block separator is a run of dashes, which looks exactly
                # like a bullet to a naive `startswith("-")` and got imported
                # as a key point on the first test.
                if not line or set(line) <= {"-"}:
                    continue
                if line.startswith("-"):
                    v = line[1:].strip()
                    # Skip the empty "-" placeholders the template ships with.
                    if v:
                        items.append(v)
            return items

        kp = bullets(m.group("kp"))
        if not kp:
            continue  # deliberately left blank -> skip, don't half-import
        out[rid] = {"key_points": kp, "common_errors": bullets(m.group("ce"))}
    return out


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--emit", type=int, default=0, help="write a worksheet of N questions")
    parser.add_argument("--fix-gold", action="store_true",
                        help="emit gold records whose rubric is still machine-drafted")
    parser.add_argument("--ingest", type=Path, default=None, help="read a completed worksheet back")
    parser.add_argument("--category", default=None, help="restrict --emit to one category")
    parser.add_argument("--target", type=int, default=15, help="per-category goal that drives selection")
    parser.add_argument("--candidates", type=Path, default=CANDIDATES_PATH)
    parser.add_argument("--gold", type=Path, default=GOLD_PATH)
    parser.add_argument("--out", type=Path, default=None)
    parser.add_argument("--author", default="", help="recorded in rubric_source, e.g. 'judge:LX'")
    args = parser.parse_args()

    gold = load_jsonl(args.gold)

    if args.fix_gold:
        stale = [r for r in gold if needs_authoring(r)]
        if not stale:
            print("every gold record already has a hand-authored rubric")
            return
        out = args.out or WORKSHEET_DIR / "fix_gold.txt"
        emit(stale, out)
        print("\nThese are already IN the gold set with machine-drafted rubrics —\n"
              "rewriting them raises the quality of the set you already have.")
        return

    if args.emit:
        candidates = load_jsonl(args.candidates)
        if not candidates:
            raise SystemExit(f"{args.candidates} not found — run scripts/rulesguru_to_gold.py first")
        picked = pick_candidates(candidates, gold, args.emit, args.category, args.target)
        if not picked:
            raise SystemExit("no unused candidates matched — try a different --category")
        name = f"author_{args.category.replace('/', '-').replace(' ', '_')}.txt" if args.category else "author.txt"
        emit(picked, args.out or WORKSHEET_DIR / name)
        return

    if args.ingest:
        authored = parse_worksheet(args.ingest.read_text(encoding="utf-8"))
        if not authored:
            raise SystemExit("no completed blocks found — did you fill in KEY POINTS?")

        by_id = {r["id"]: r for r in gold}
        candidates = {c["id"]: c for c in load_jsonl(args.candidates)}
        source = f"hand-authored ({args.author})" if args.author else "hand-authored"
        source += "; decomposed from the source's verified answer, not judge-reviewed"

        updated = added = skipped = 0
        problems: list[str] = []
        for rid, rub in authored.items():
            if len(rub["key_points"]) < 2:
                problems.append(f"{rid}: only {len(rub['key_points'])} key point — the validator needs 2+")
                skipped += 1
                continue
            if rid in by_id:
                by_id[rid].update(key_points=rub["key_points"], common_errors=rub["common_errors"],
                                  rubric_source=source, needs_rubric_review=False)
                updated += 1
            elif rid in candidates:
                rec = dict(candidates[rid])
                rec.update(key_points=rub["key_points"], common_errors=rub["common_errors"],
                           rubric_source=source, needs_rubric_review=False, needs_review=True)
                gold.append(rec)
                added += 1
            else:
                problems.append(f"{rid}: not found in gold or candidates")
                skipped += 1

        with args.gold.open("w", encoding="utf-8") as f:
            for r in gold:
                f.write(json.dumps(r, ensure_ascii=False) + "\n")

        print(f"{added} promoted, {updated} rewritten, {skipped} skipped -> {args.gold}")
        no_errors = [rid for rid, r in authored.items() if not r["common_errors"]]
        if no_errors:
            print(f"\n{len(no_errors)} block(s) have no COMMON ERRORS. That field is half the "
                  f"rubric's power and cannot be derived from the answer — worth a second pass:")
            print("  " + ", ".join(no_errors[:8]))
        if problems:
            print(f"\n{len(problems)} problem(s):")
            for p in problems:
                print(f"  - {p}")
        print("\nNext: python scripts/validate_gold.py --to-eval")
        return

    parser.error("choose one of --emit, --fix-gold, or --ingest")


if __name__ == "__main__":
    main()
